### PR TITLE
Feature/munjung sbnd om 20240816

### PR DESCRIPTION
**Pull request by wjdanswjddl**
### Description

Updates to SBND DQM modules for all subsystems: TPC, PMT, CRT, Timing, Trigger. A master fcl that runs all subsystem streams were made for SBND operations shifter runs.

### Testing details

All updates are specific to SBND, and were tested on online SBND runs.

### CODE REVIEW

**Review by mking99456 — APPROVED** [review]
Wow looks great

**Comment by mvicenzi** [comment]
I'm not sure why, but github is complaining about minor conflicts...
@wjdanswjddl Would you able to clear them out so we can merge this into `release/v1_03_00`?

**Comment by wjdanswjddl** [comment]
@mvicenzi I resolved the conflicts

**Comment by mvicenzi** [comment]
> @mvicenzi I resolved the conflicts

Thank you! 
I was ready to merge things, but then I noticed that there are some changes affecting the common TPC/CRT modules.
It looks ok for the CRT (just some new metrics being sent), but I see new code working with `raw::RDTimeStamp` objects in the TPC and I'm note sure if these are available for ICARUS... so I worry it might break things.
I'm going to check with @hausnerh !

**Comment by wjdanswjddl** [comment]
@mvicenzi yeah those were added for monitoring broken events in SBND. If it causes issues for ICARUS, then I suggest making separate directories for SBND/ICARUS for TPCs as well

**Comment by hausnerh** [comment]
ICARUS does not produce `raw::RDTimeStamp`s. Maybe we should, I don't know, but that'd be a different pull request regardless

**Comment by mvicenzi** [comment]
Thanks @hausnerh ! Yeah, so I agree with you @wjdanswjddl ... let's go with separate directories so we make sure there is no interference whatsoever. I can help with that if needed :)

**Comment by wjdanswjddl** [comment]
> I'm not sure why, but github is complaining about minor conflicts... @wjdanswjddl Would you able to clear them out so we can merge this into `release/v1_03_00`?

@mvicenzi Looks like this `release/v1_03_00` -> `feature/munjung-SBND_OM_20240816` merge updated some CMakeLists and caused compile errors on the SBND side. We'll need to update the files to fix that and commit again. On a related note, it seems like the commits that updated the CMakeLists came from the ICARUS side -- is there an active ICARUS `sbndqm` PR open, or is everything already merged into  `release/v1_03_00` already?

**Comment by mvicenzi** [comment]
> > I'm not sure why, but github is complaining about minor conflicts... @wjdanswjddl Would you able to clear them out so we can merge this into `release/v1_03_00`?
> 
> @mvicenzi Looks like this `release/v1_03_00` -> `feature/munjung-SBND_OM_20240816` merge updated some CMakeLists and caused compile errors on the SBND side. We'll need to update the files to fix that and commit again. On a related note, it seems like the commits that updated the CMakeLists came from the ICARUS side -- is there an active ICARUS `sbndqm` PR open, or is everything already merged into `release/v1_03_00` already?

The only ICARUS PR we had for this release (#36) has already been merged into `release/v1_03_00`. 
We are not going to add anything else on the ICARUS side.

**Comment by wjdanswjddl** [comment]
I'm closing this and opening another PR

**Pull request closed without merging**
