### PR TITLE
SBND CRT DQM for DQM Software Release

### PR DESCRIPTION
**Pull request by mking99456**
### Description

This pull request is for the /sbndqm/dqmAnalysis/CRT folder - specifically, the BernModule and online and offline fcl files. These three files should be included in the next DQM release.

### CODE REVIEW

**Review by betan009 — APPROVED** [review]
The updates looks good to me

**Review by gennadiy-fnal — CHANGES_REQUESTED** [review]
The description of the pull request is not specific enough to assess if the proposed implementation is valid. Please update the description. Also, please provide reproducible testing instructions.

**Comment by mking99456** [comment]
This module runs using artdaq_core v3_07_04, sbncode v09_43_00, and sbndqm version v1_00_00_e20_prof. 

My setup script is:

ksu sbnddqm
cd /home/nfs/sbnddqm/DQM_DevAreas/mking_CRT_DQM_dev/
source /software/products/setup
source /software/products_dev/setup
setup mrb
export MRB_PROJECT=sbndqm
source localProducts_sbndqm_1_00_00_e20_prof/setup
mrbsetenv
cd srcs/sbndqm/sbndqm/dqmAnalysis/CRT/

I tested this module on offline data files using this build, and it worked successfully. I believe it also worked for the online test, but I'm not 100% sure.

To test offline, run lar -c crt_FEBmetrics_offline.fcl -s <test_CRT_file.root>

To test online, run on the same event builder as the DAQ, python daq_consumer.py -f crt_FEBmetrics_online.fcl -l <log_file_directory>

**Review by gennadiy-fnal — APPROVED** [review]
I haven't had a chance to verify the functionality of this code, and approving this PR is in accordance with @betan009 request.

**Comment by mvicenzi** [comment]
This PR was already merged into `release/v1_03_00` with https://github.com/SBNSoftware/sbndqm/commit/12e42ab41287f97b9640193fc20983fda82ef137.
Closing to clean up.

**Pull request closed without merging**
